### PR TITLE
Project card event added support & input labels list guards

### LINKED ISSUE #10: Label not being removed on issue close event
Is this a configuration error on my end?

`labeler.yml`
```
# This workflow fires when an issue is closed, and removes the "in progress" label
name: Remove 'in progress' label from closed issue

on:
  issues:
    types: [closed]

jobs:
  remove-label:
    runs-on: ubuntu-latest
    steps:
    - uses: andymckay/labeler@1.0.2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        remove-labels: "bug"
```

`output`
```Run andymckay/labeler@1.0.2
  with:
    repo-token: ***
    remove-labels: bug
RequestError [HttpError]: Validation Failed
    at /home/runner/work/_actions/andymckay/labeler/1.0.2/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async label (/home/runner/work/_actions/andymckay/labeler/1.0.2/label.js:48:3) {
  name: 'HttpError',
  status: 422,
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
    connection: 'close',
    'content-length': '177',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Wed, 25 Mar 2020 22:14:11 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '422 Unprocessable Entity',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
```

### LINKED ISSUE #12: Cannot read number of 'undefined' Project Card event
The same error happen from issue #6 when this action is called with `project_card` event. I would like to use it to add a label to my issue from a `project_car` event.

```yml
name: project-automation

on:
  project_card:
    types: [moved]

jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: label issues from 'In progress'
        uses: andymckay/labeler@1.0.2
        if: |
          github.event_name == 'project_card' &&
          (
            github.event.project_card.column_id == 9034006
          )
        with:
          repo-token: ${{secrets.GH_TOKEN}}
          add-labels: "c"
```

image

### PR DESCRIPTION
**Pull request by rodrigondec**
I made my PR based on #11. I recommend to wait for the PR #11 to be merged to be sure there's no conflict.

Uses `context.payload.project_card.issues` to get the `issueNumber` from url if `context.payload.issue.number` and `context.payload.pull_request` are undefined.

This should fix #12.
this should fix #10.

### CODE REVIEW

**Comment by andymckay** [comment]
Thanks @rodrigondec, I've merged #11. Sorry I was on vacation and missed this. I'll try take a more detailed look in the next day or so.

File: label.js [hunk 1]
```diff
@@ -19,7 +19,20 @@ async function label() {
...
+
+  if (context.payload.issue !== undefined) {
+    issueNumber = context.payload.issue.number;
+  } else if (context.payload.pull_request !== undefined) {
+    issueNumber = context.payload.pull_request.number;
+  } else if (context.payload.project_card !== undefined) {
+    var issuesUrl = context.payload.project_card.issues_url;
+    var urlArray = issuesUrl.split("/");
+    issueNumber = urlArray[urlArray.length - 1];
+    if (issueNumber == "issues") {
```
Comment (andymckay) [inline label.js]: Sorry, it looks like this is trying to check that this `issue_url` does not end in `issues`. I was curious when that was, looking at the docs for the webhook event: https://developer.github.com/webhooks/event-payloads/#project_card it looks like it should have a `number` on the end of it?

File: label.js [hunk 2]
```diff
@@ -19,7 +19,20 @@ async function label() {
...
+  var issueNumber;
+
+  if (context.payload.issue !== undefined) {
+    issueNumber = context.payload.issue.number;
+  } else if (context.payload.pull_request !== undefined) {
+    issueNumber = context.payload.pull_request.number;
+  } else if (context.payload.project_card !== undefined) {
+    var issuesUrl = context.payload.project_card.issues_url;
+    var urlArray = issuesUrl.split("/");
+    issueNumber = urlArray[urlArray.length - 1];
```
Comment (andymckay) [inline label.js]:
```suggestion
    issueNumber = context.payload.project_card.issues_url.split("/").pop()
```

Although shorter may not always be clearer 😄

File: README.md [hunk 3]
```diff
@@ -1,39 +1,109 @@
...
+They also may be used together. 
 
 ```yml
-    - uses: andymckay/labeler@1.0.2
-      with:
-        repo-token: "${{ secrets.GITHUB_TOKEN }}"
-        add-labels: "needs-triage, bug"
-        ignore-if-assigned: true
+add-labels: 'label1, label2'
+remove-labels: 'label1, label2'
```
Comment (andymckay) [inline README.md]:
```suggestion
remove-labels: 'label3, label4'
```

Just to prevent user confusion why they are adding and removing the same label.

File: README.md [hunk 4]
```diff
@@ -1,39 +1,109 @@
...
+    types: [opened]
+  project_card:
+    types: [moved]
+
+jobs:
+  automate-issues-labels:
+    runs-on: ubuntu-latest
+    steps:
+      - name: initial labeling
+        uses: andymckay/labeler@1.0.2
```
Comment (andymckay) [inline README.md]: Could make this `@master` please. It goes against some of the guidance, but then we won't need to change this each time we do a release. I'd like to do one after this has merged in.

File: README.md [hunk 5]
```diff
@@ -1,39 +1,109 @@
...
+
+on:
+  issues:
+    types: [assigned]
+
+jobs:
+  automate-issues-labels:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: andymckay/labeler@1.0.2
```
Comment (andymckay) [inline README.md]: Same here.

**Review by andymckay — APPROVED** [review]
👍 Thank you and sorry for the slow reply. If you could take a look at a few of the comments and then we can merge 🙇

File: label.js (hunk 2 above)
Comment (rodrigondec) [reply label.js]: I don't mind. I'm not a JS developer :rofl:

File: README.md (hunk 4 above)
Comment (rodrigondec) [inline README.md]:
```suggestion
        uses: andymckay/labeler@master
```

File: README.md (hunk 5 above)
Comment (rodrigondec) [reply README.md]:
```suggestion
      - uses: andymckay/labeler@master
```

File: label.js (hunk 1 above)
Comment (rodrigondec) [reply label.js]: Yes, that was my intention. Because it's not every card that has a issue.

I didn't find a better way. Either on https://developer.github.com/webhooks/event-payloads/#project_card

or https://developer.github.com/v3/projects/cards/.

Maybe there's a better way?

Comment (rodrigondec) [reply label.js]: Looking at the object, the following declaration may be wrong:
```js
var issuesUrl = context.payload.project_card.issues_url;
```

There's some way to test it?

**Comment by andymckay** [comment]
Sorry I was confused what you were trying to do, so I played around a little. So I think you are trying to label an issue when it moves between columns on a project board. If that's the case here's what I found out.

There's two kinds of things on a project board, a not3e and an issue. Confusingly the event name is the same for both.

When I move an issue between columns on a project board I get this:

```
{
  action: 'moved',
  project_card: {
  ...
    content_url: "https://api.github.com/repos/andymckay/sandbox/issues/9",
     note: null
  ...
```

When I move a note between columns on a project board I get this:

```
{
  action: 'moved',
  project_card: {
    ...
    note: "Text of the note"
    ...
```

But in this case no `content_url`.

If that's what you are trying to do I suggest:
* check for the presence of `content_url`
* parse on that

So something like:

```
  } else if (context.payload.project_card !== undefined && context.payload.project_card.content_url) {
    issueNumber = context.payload.project_card.content_url.split("/").pop()
  }
```

Might work. If you want to test this out, I normally set up a quick repo and run the code locally, you can see how I did that here: https://github.com/andymckay/sandbox/blob/master/.github/workflows/main.yml#L12, using the code in here: https://github.com/andymckay/sandbox/blob/master/label.js

**Review by andymckay — CHANGES_REQUESTED** [review]
Based on that this won't work, asking for some changes.

**Comment by rodrigondec** [comment]
That was exaclty what I wanted to do. Thank you for your invested time.

I'll improve this PR with the considerations on this week :smile:

**Comment by rodrigondec** [comment]
@andymckay 

It's alive. I tested with a sandbox repo like you intructed.

https://github.com/rodrigondec/labeler-sandbox

Some samples are already on this comment https://github.com/andymckay/labeler/issues/10#issuecomment-636506899

**Review by andymckay — APPROVED** [review]
Looks awesome, thanks @rodrigondec for making those additional changes.
